### ISSUE TITLE
Cannot create proposal

### ISSUE THREAD

**Issue by PeterNerlich** [Max-F-Helm/Signage#4]
Creating a proposal with one other identity added as author fails:

```
unable to create proposal: author load failed RangeError: Trying to access beyond buffer length
    at Ln (index.063238cf.js:367:13140)
    at b.readUint8.b.readUInt8 (index.063238cf.js:367:13628)
    at Vi.readUInt8 (index.063238cf.js:396:570018)
    at Vi.readStringUtf8 (index.063238cf.js:396:571051)
    at sn.loadAuthor (index.063238cf.js:396:572183)
    at Fe (index.063238cf.js:1393:3601)
    at async le (index.063238cf.js:1393:2719)
```

**Comment by Max-F-Helm** [comment]
I have enables sourcemaps. Please retry it and comment the new stacktrace with a short description of your actions.

**Comment by PeterNerlich** [comment]
- I created two identities and saved their files locally (second on in incognito browser)
- Loading the page, I select the stored identity
- Opting to create a new proposal, I select the second `.sIdn` file (from the incognito browser) as the other author
- As soon as I click on *Create*, the message *there was an error while creating the proposal (author-file identity (1).sIdn is corrupted)* appears, along with the following trace in the console:

```
16:14:04.669 DocNew.vue:149 unable to create proposal: author load failed RangeError: Trying to access beyond buffer length
    at Ln (index.js:1127:36)
    at b.readUint8.b.readUInt8 (index.js:1166:18)
    at Ji.readUInt8 (buffer-reader.ts:48:31)
    at Ji.readStringUtf8 (buffer-reader.ts:128:20)
    at sn.loadAuthor (identity-processor.ts:59:27)
    at ge (DocNew.vue:197:30)
    at async E (DocNew.vue:136:26)
E @ DocNew.vue:149
await in E (async)
Xa @ runtime-core.esm-bundler.js:157
kr @ runtime-core.esm-bundler.js:166
a @ runtime-dom.esm-bundler.js:345
```

All passwords (for the identities and the proposal) were `test1234`.

**Comment by Max-F-Helm** [comment]
as mentioned in my comment in #3 you have to use the .sAut file for the authors, not .sIdn.
